
stages:
  - stage: build_natives
    jobs:
    - job: build_win32_natives
      pool:
        vmImage: 'windows-2019'
      strategy:
        matrix:
          Debug:
            CMAKE_BUILD_TYPE: 'Debug'
          Release:
            CMAKE_BUILD_TYPE: 'Release'
      steps: 
      - bash: echo "This is Win32 ${CMAKE_BUILD_TYPE}"
      - bash: cmake
      - bash: msbuild /property:Configuration=${CMAKE_BUILD_TYPE}
    - job: build_macos_natives
      pool:
        vmImage: 'macOS-10.14'
      strategy:
        matrix:
          Debug:
            CMAKE_BUILD_TYPE: 'Debug'
          Release:
            CMAKE_BUILD_TYPE: 'Release'
      steps:
      - bash: echo "This is MacOS ${CMAKE_BUILD_TYPE}"
      - bash: cmake -D ${CMAKE_BUILD_TYPE}
      - bash: make
    - job: build_linux_natives
      pool:
        vmImage: 'ubuntu-16.04'
      strategy:
        matrix:
          Debug:
            CMAKE_BUILD_TYPE: 'Debug'
          Release:
            CMAKE_BUILD_TYPE: 'Release'
      steps: 
      - bash: echo "This is Linux ${CMAKE_BUILD_TYPE}"
      - bash: cmake -D ${CMAKE_BUILD_TYPE}
      - bash: make
  - stage: build_java
    jobs:
    - job: build_java
      steps:
      - bash: mvn package

