
stages:
  - stage: build_natives
    displayName: Natives
    jobs:
    - job: build_win32_natives
      displayName: Win32
      pool:
        vmImage: 'windows-2019'
        demands:
        - msbuild
        - visualstudio
      strategy:
        matrix:
          Debug:
            CMAKE_BUILD_TYPE: 'Debug'
          Release:
            CMAKE_BUILD_TYPE: 'Release'
      steps:
      - bash: '.azure-pipelines/build-win32.sh'
    - job: build_macos_natives
      displayName: MacOS
      pool:
        vmImage: 'macOS-10.14'
      strategy:
        matrix:
          Debug:
            CMAKE_BUILD_TYPE: 'Debug'
          Release:
            CMAKE_BUILD_TYPE: 'Release'
      steps:
      - bash: .azure-pipelines/build-unix.sh
    - job: build_linux_natives
      displayName: Linux
      pool:
        vmImage: 'ubuntu-16.04'
      strategy:
        matrix:
          Debug:
            CMAKE_BUILD_TYPE: 'Debug'
          Release:
            CMAKE_BUILD_TYPE: 'Release'
      steps: 
      - bash: .azure-pipelines/build-unix.sh
  - stage: build_java
    jobs:
    - job: build_java
      steps:
      - bash: mvn package

